### PR TITLE
Add metrics part

### PR DESCRIPTION
**Pull request by ChrsMark**

### CODE REVIEW

**Comment by ChrsMark** [comment]
Same status as https://github.com/elastic/observability-docs/pull/154

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/doc rebuild

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by dedemorton** [comment]
Hmm... Looks like the doc preview won't work when the base is a feature branch? I forced a full rebuild to fix the 404 I was getting, but the updates aren't there.

I'm OK with building locally, but disappointed. Maybe when @gtback is back on Monday, he figure out how to get the docs PR build to work with a feature branch. I'll just build locally for now.

**Comment by gtback** [comment]
I don't have a good answer for this, sorry. I can understand the diff being confusing, since it will be compared to "master", not to some docs built on the base branch of this PR. But I'm not sure why the page doesn't show up at all; possibly because it's a new page in the base branch of the PR as well, or because it doesn't know which "primary" branch (master, 7.x, 7.9, etc.) to base all of this on.

**Review by dedemorton — APPROVED** [review]
Let's merge this into the feature branch so I can iterate on it. See related comment here: https://github.com/elastic/observability-docs/pull/154#issuecomment-705886155

**Pull request merged**
