### PR TITLE
Uptime app: Update content and images for 7.14

### PR DESCRIPTION
**Pull request by EamonnTP**
### Summary

This PR updates content and images to reflect the UI updates for the 7.14 release. 

### Docs preview

https://observability-docs_840.docs-preview.app.elstc.co/guide/en/observability/master/monitor-uptime.html

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Thanks for updating the RAC content while you were here!

dance

**Review by paulb-elastic — COMMENTED** [review]
All LGTM with the exception of one thing I am unsure of, regarding `heartbeat-indices.png`.

The [current version](https://github.com/elastic/observability-docs/blob/7.13/docs/en/observability/images/heartbeat-indices.png) of the image in the docs shows the default as being `heartbeat-8*` whereas the [new version](https://github.com/EamonnTP/observability-docs/blob/uptime-alert-terms/docs/en/observability/images/heartbeat-indices.png) of the image in the docs suggests `heartbeat-8*,synthetics-*`.

I think both are wrong for the 7.14 release, which I think should be `heartbeat-7*,synthetics-*`?  I think this may be because the screen shots have been taken from `edge` (tracking `master`) as opposed to `release`.

@shahzad31 / @vigneshshanmugam - is my suggestion correct, should the default for 7.14 be `heartbeat-7*,synthetics-*`?

**Comment by bmorelli25** [comment]
> I think both are wrong for the 7.14 release, which I think should be `heartbeat-7*,synthetics-*`?

That's what I'm seeing as well. Eamonn is out, so I've updated the screenshot. Will wait for Shazad or V to verify before merging.

**Comment by vigneshshanmugam** [comment]
> is my suggestion correct, should the default for 7.14 be heartbeat-7*,synthetics-*?

++ This should be the default for 7.14

**Comment by bmorelli25** [comment]
Thanks!

**Comment by EamonnTP** [comment]
Thanks @bmorelli25 for taking care of this while I was off.

**Pull request merged**
