### PR TITLE
Update and rename doc-preview.yml to docs-preview.yml

### PR DESCRIPTION
**Pull request by bmorelli25**
Move away from our own custom implementation of commenting on PRs to the [shared implementation](https://github.com/elastic/docs/blob/master/.github/workflows/doc-preview.yml).

### CODE REVIEW

**Review by colleenmcginnis — APPROVED** [review]
🙏

**Comment by bmorelli25** [comment]
bump bump

**Comment by bmorelli25** [comment]
oh wow just needed to refresh

**Comment by bmorelli25** [comment]
Backports are failing because this check wasn't backported to old versions. I'm just gonna take it back.

**Pull request merged**
