### PR TITLE
Complete the explanation for the files in the integration field directory

### PR DESCRIPTION
**Pull request by Oddly**
Small addition to the explanation of what each file in the data_stream/fields directory does. 
- agent.yml provides the fields the Elastic agent uses.
- fields.yml are additional fields the integration uses.

### CODE REVIEW

**Comment by bmorelli25** [comment]
Thanks, @Oddly! Can you please sign the CLA linked above in https://github.com/elastic/observability-docs/pull/3757#issuecomment-2056875244.

**Comment by bmorelli25** [comment]
run docs-build

**Comment by Oddly** [comment]
CLA signed. Should I run something again?

**Review by bmorelli25 — APPROVED** [review]

**Comment by bmorelli25** [comment]
Thanks again!

**Pull request merged**
