### PR TITLE
Fleet server: updating the troubleshooting info

### PR DESCRIPTION
**Pull request by EricDavisX**
This is a pretty rough start at updates, but it is content.  And I trust the Docs team to take it and make it more better for our users, hope it helps!

attempt at contributing towards:
https://github.com/elastic/observability-docs/issues/526

### Docs preview:

https://observability-docs_616.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-troubleshooting.html

### CODE REVIEW

**Comment by dedemorton** [comment]
Would you mind making the title of this PR more descriptive? It will become the commit message. Maybe indicate that you're updating the troubleshooting info.

**Comment by EamonnTP** [comment]
Thanks @EricDavisX If you don't mind, I'll make changes directly to your branch.

**Comment by EamonnTP** [comment]
Hi @EricDavisX Along with your recent additions, I did an edit review of whole Troubleshooting topic. If you are happy with my updates, should we go ahead and merge this PR? We can always have followup PR's for any outstanding troubleshooting issues listed in #526

**Review by EamonnTP — COMMENTED** [review]
Hi @EricDavisX Along with your recent additions, I did an edit review of whole Troubleshooting topic. If you are happy with my updates, should we go ahead and merge this PR? We can always have followup PR's for any outstanding troubleshooting issues listed in #526

**Review by EricDavisX — COMMENTED** [review]
i love it - let's merge and keep iterating

**Pull request merged**
