### PR TITLE
Ports #3975 to serverless

### PR DESCRIPTION
**Pull request by dedemorton**
## Description
Ports #3957 to serverless.

Also adds a missing period.

### Documentation sets edited in this PR

_Check all that apply._

- [ ] Stateful (`docs/en/observability/*`)
- [x] Serverless (`docs/en/serverless/*`)
- [ ] Integrations Developer Guide (`docs/en/integrations/*`)
- [ ] None of the above

### Related issue
n/a

## Checklist

- [ ] Product/Engineering Review
- [x] Writer Review

### Follow-up tasks

_Select one._

* This PR does _not_ need to be ported to another doc set because:
  - [ ] The concepts in this PR only apply to one doc set (serverless _or_ stateful)
  - [ ] The PR contains edits to both doc sets (serverless _and_ stateful)
  - [x] This PR _is_ a port.
* This PR needs to be ported to another doc set:
  - [ ] Port to stateful docs: \<link to PR or tracking issue>
  - [ ] Port to serverless docs: \<link to PR or tracking issue>

### CODE REVIEW

**Comment by dedemorton** [comment]
@bmorelli25 I'm loving the PR template, but there's a missing state: "This PR is a port" (not sure that's the best wording, but saying "The concepts in this PR only apply to one doc set (serverless or stateful)" isn't correct if the PR is a port from one doc set to another.

**Comment by elasticdocs** [comment]
:rocket: Built _elastic-dot-co-docs-preview-docs_ successfully!

* https://elastic-dot-co-docs-production-f85c6nr02-elastic-dev.vercel.app

* Built with commit 4f92b293a92ab0925c67a26e9d664e96a6253e50

> Issues? Visit #next-docs in Slack

**Comment by colleenmcginnis** [comment]
@dedemorton @bmorelli25  I wonder if we just add a comment that instructs the author to delete the template and just add a comment with a link for ports: "This is a port of #". Then there is a single source of truth for info about the changes -- the initial PR that is being ported.

**Review by colleenmcginnis — APPROVED** [review]
✨

**Pull request merged**
