### PR TITLE
Update link to future package spec

### PR DESCRIPTION
**Pull request by jsoriano**
We are changing how to handle multiple versions in the package spec repository.

To be merged after https://github.com/elastic/package-spec/pull/384.

### CODE REVIEW

**Review by mtojek — COMMENTED** [review]
LGTM

**Review by bmorelli25 — APPROVED** [review]
👍 Makes sense.

Side note: should we remove this book from the documentation build? https://github.com/elastic/elastic-package/tree/main/docs/howto is much more up-to-date than this content is.

**Review by mtojek — APPROVED** [review]

**Comment by jsoriano** [comment]
CI failing also with the new paths:
```
INFO:build_docs:asciidoctor: ERROR: package-spec.asciidoc: line 80: include file not found: /tmp/docsbuild/D8jIG7hR5Z/package-spec/spec/integration/spec.yml
INFO:build_docs:asciidoctor: ERROR: package-spec.asciidoc: line 94: include file not found: /tmp/docsbuild/D8jIG7hR5Z/package-spec/spec/integration/_dev/spec.yml
INFO:build_docs:asciidoctor: ERROR: package-spec.asciidoc: line 108: include file not found: /tmp/docsbuild/D8jIG7hR5Z/package-spec/spec/integration/data_stream/spec.yml
INFO:build_docs:asciidoctor: ERROR: package-spec.asciidoc: line 122: include file not found: /tmp/docsbuild/D8jIG7hR5Z/package-spec/spec/integration/docs/spec.yml
INFO:build_docs:asciidoctor: ERROR: package-spec.asciidoc: line 136: include file not found: /tmp/docsbuild/D8jIG7hR5Z/package-spec/spec/integration/kibana/spec.yml
INFO:build_docs:asciidoctor: ERROR: package-spec.asciidoc: line 150: include file not found: /tmp/docsbuild/D8jIG7hR5Z/package-spec/spec/integration/changelog.spec.yml
INFO:build_docs:asciidoctor: ERROR: package-spec.asciidoc: line 165: include file not found: /tmp/docsbuild/D8jIG7hR5Z/package-spec/spec/integration/manifest.spec.yml
```

Opened https://github.com/elastic/package-spec/pull/401 to avoid blocking builds.

We will need to find a better solution to import spec documentation that doesn't rely on the source files for the spec https://github.com/elastic/package-spec/pull/400.

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
No need to backport this as we only publish one version of these docs.

**Comment by bmorelli25** [comment]
It should now be safe to revert https://github.com/elastic/package-spec/pull/401.

**Comment by jsoriano** [comment]
> No need to backport this as we only publish one version of these docs.

So only the main branch is built? If we revert https://github.com/elastic/package-spec/pull/401 without backporting, would it affect builds for 7.17?

**Comment by jsoriano** [comment]
> Correct, only the main branch is built. Backporting to any other branch is not required. The branches (or in this case, branch) to build is defined here: https://github.com/elastic/docs/blob/master/conf.yaml#L1817.

Ok, I will revert the change in package-spec then, thanks!

**Pull request merged**
