### PR TITLE
Add Fleet and Agent release notes for 7.13.2

### PR DESCRIPTION
**Pull request by dedemorton**
Copies over release notes from Kibana so that they appear in the Fleet User Guide.

Do we need to add anything else? Anything for Elastic Agent?

### CODE REVIEW

**Review by jen-huang — APPROVED** [review]
Fleet stuff looks good, thanks!

**Review by bmorelli25 — APPROVED** [review]
Can't comment on content, but the build looks good https://observability-docs_787.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-7.13.2.html

**Comment by ph** [comment]
@urso Anything we are missing from Agent in 7.13.2?

**Comment by dedemorton** [comment]
I'm gonna merge to get this in today. @urso Just ping me if you have more stuff to add. Thanks!

**Pull request merged**
