### PR TITLE
Fixes two small errors in Fleet Server Docs

### PR DESCRIPTION
**Pull request by EricDavisX**
Fixes:
https://github.com/elastic/observability-docs/issues/722
https://github.com/elastic/observability-docs/issues/723

Thank you to QAS team for finding them, all of the fixes we can put in make the docs easier and experience better.

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Thanks, Eric!

**Comment by EricDavisX** [comment]
Thanks @bmorelli25

**Review by dedemorton — COMMENTED** [review]
LGTM. Not sure how/why those slashes got introduced. :-)

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this PR and found it as **fixed** now. 

**Screenshots:**
For https://github.com/elastic/observability-docs/issues/722 :


For https://github.com/elastic/observability-docs/issues/723 :
10 - Copy


Thanks
QAS

**Pull request merged**
