### PR TITLE
Update elastic-agent Url docker official repo

### PR DESCRIPTION
**Pull request by rschirin**
Update elastic-agent-container.asciidoc Url for docker official repository

### CODE REVIEW

**Comment by EamonnTP** [comment]
Many thanks @rschirin for your contribution. Would you mind signing the [Contributor agreement](https://www.elastic.co/contributor-agreement).

**Comment by rschirin** [comment]
> Many thanks @rschirin for your contribution. Would you mind signing the [Contributor agreement](https://www.elastic.co/contributor-agreement).

@EamonnTP I did it! It should be OK now

**Comment by EamonnTP** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Review by EamonnTP — APPROVED** [review]
Thanks @rschirin looks good! Once squashed and merged to the `master` branch, you will need to back port the PR to the `7.x` and `7.15` branches. Let me know if you need any help with this.

**Comment by dedemorton** [comment]
@rschirin I will take care of the backports. Thanks!

**Pull request merged**
