### PR TITLE
Update Fleet Server diagram

### PR DESCRIPTION
**Pull request by kilfoyle**
This updates the [What is Fleet Server?](https://www.elastic.co/guide/en/fleet/current/fleet-server.html#_what_is_fleet_server) diagram to:
 - say "Fleet UI in Kibana"
 - include the Agent and Fleet icons
 - show the policy movement in both directions between Fleet and Agent, and between Fleet and Elasticsearch. 

The diagram is embedded as an SVG file so that it's easy to update. For reference, the Figma source is [here](https://www.figma.com/file/uOJxDPjLrKOXEqZxegcf0V/What-is-Fleet-Server?node-id=18%3A30&t=z5nqOK5G22aK8DbP-0).

Closes: #2038 

**original**
original

**proposed** 
updated with corrected colors per Karen's [suggestion](https://github.com/elastic/observability-docs/pull/2580#pullrequestreview-1287347887)
Screenshot 2023-02-08 at 7 48 30 PM

### CODE REVIEW

**Comment by dedemorton** [comment]
Looks good. I wonder if we should change  "enroll & get policy" to  "enroll"? I think the second arrow makes it clear that Fleet Server returns a policy, so I don't think "get policy" is necessary because from the user's perspective...they just have to install/enroll the agent.

cc'ing @karenzone because she's been working on some similar diagrams.

**Comment by kilfoyle** [comment]
Good idea! I've updated the diagram as suggested ("enroll & get policy" to "enroll").

**Review by dedemorton — APPROVED** [review]
LGTM. Would be good for @karenzone to take a look if she has time.

**Review by karenzone — COMMENTED** [review]
Nicely clarifies additional details. Thank you. 

I believe that color assignment for products is set by our brand strategy team. IIRC, Beats is blue, Elasticsearch is teal, Logstash is yellow, Kibana is pink, for example. I will try to get a definite answer.

**Comment by kilfoyle** [comment]
Thanks @karenzone! For now, I've updated the colors so that Elasticsearch is teal and Elastic Agent is blue. If there's an official list of product colors somewhere that would be superb.

**Comment by karenzone** [comment]
Thanks, David.  I'm not sure if we have an assigned color for Fleet Server. It might be blue because Fleet Server is actually a souped up Elastic Agent with super powers. ⚡ 

@KOTungseth: 
>If there's an official list of product colors somewhere that would be superb.

Let's be sure that we're aware and aligned on brand colors and other style issues across our docs. Fits in quite nicely with our new org structure.

**Comment by KOTungseth** [comment]
> Thanks, David. I'm not sure if we have an assigned color for Fleet Server. It might be blue because Fleet Server is actually a souped up Elastic Agent with super powers. ⚡
> 
> @KOTungseth:
> 
> > If there's an official list of product colors somewhere that would be superb.
> 
> Let's be sure that we're aware and aligned on brand colors and other style issues across our docs. Fits in quite nicely with our new org structure.

Yes! Great points. For consistency between /guide, elastic.co pages, and our UIs, we've been using:

- [EUI](https://elastic.github.io/eui/#/display/icons) for icons
- Our Branding color guidelines, which you can find on the Wiki

It looks like this is the official icon for Elastic Agent:
Screenshot 2023-02-08 at 12 27 01 PM

And this is the official icon for Fleet app (I'm not sure if this also covers Fleet Server since the Fleet Server is what connects Fleet and Elastic Agent):
Screenshot 2023-02-08 at 12 31 40 PM

For the coloring, I'm fairly certain the apps don't get designated colors, so we might consider rendering the background white.

**Comment by kilfoyle** [comment]
Thanks all! I've updated the backgrounds as Kaarina suggested and the outline colors as Karen suggested.

@KOTungseth Thanks for pointing to that [EUI icons list](https://elastic.github.io/eui/#/display/icons). Unless I'm mistaken, the agentApp and fleetApp icons are reversed. I've opened [this issue](https://github.com/elastic/eui/issues/6584) to get that fixed up.

The updated image is in the description and I'll merge this puppy tomorrow.

**Pull request merged**
