### PR TITLE
Port #4340 to stateful: Update EEM to reflect Inventory

### PR DESCRIPTION
**Pull request by alaudazzi**
## Description
This PR updates the EEM section to reflect Inventory (port https://github.com/elastic/observability-docs/pull/4340 to stateful). 

**NOTE FOR REVIEWERS: CI checks are failing because this PR has dependencies on https://github.com/elastic/observability-docs/pull/4438.**

### Documentation sets edited in this PR

_Check all that apply._

- [X] Stateful (`docs/en/observability/*`)
- [ ] Serverless (`docs/en/serverless/*`)
- [ ] Integrations Developer Guide (`docs/en/integrations/*`)
- [ ] None of the above

### Related issue
Closes https://github.com/elastic/observability-docs/issues/4370

## Checklist

- [X] Product/Engineering Review
- [ ] Writer Review

### Follow-up tasks

_Select one._

* This PR does _not_ need to be ported to another doc set because:
  - [ ] The concepts in this PR only apply to one doc set (serverless _or_ stateful)
  - [ ] The PR contains edits to both doc sets (serverless _and_ stateful)
* This PR needs to be ported to another doc set:
  - [ ] Port to stateful docs: \<link to PR or tracking issue>
  - [ ] Port to serverless docs: \<link to PR or tracking issue>

### CODE REVIEW

**Comment by alaudazzi** [comment]
@roshan-elastic 
Would you mind checking if the {es} privileges are still OK?

**Review by dedemorton — APPROVED** [review]
Changes LGTM from an editorial perspective.

Build should pass after https://github.com/elastic/observability-docs/pull/4438 is merged, so I'm approving.

**Comment by roshan-elastic** [comment]
Hey @alaudazzi - sorry, missed this. I can't seem to access a page where it shows the ES privileges. Do you have a link I can check at all?

**Comment by alaudazzi** [comment]
@roshan-elastic 
these are the ES privileges:

image

**Comment by roshan-elastic** [comment]
Cheers @alaudazzi 

@tommyers-elastic  - is [this](https://github.com/elastic/observability-docs/pull/4439#issuecomment-2449353716) still accurate?

**Comment by alaudazzi** [comment]
@tommyers-elastic @roshan-elastic 
As this PR is blocking other PRs, I will merge it. We can follow up on the ES privileges in a separate PR.

**Pull request merged**
