### PR TITLE
Adding PowerShell to download and extract Endpoint agent on Windows

### PR DESCRIPTION
**Pull request by clark0r**

### CODE REVIEW

**Comment by clark0r** [comment]
Contributor agreement signed.

**Comment by bmorelli25** [comment]
Thanks for the contribution, @clark0r!

@dedemorton would you mind taking a look? I'll kick off a doc build in the meantime.

@elasticmachine, run elasticsearch-ci/docs

**Review by dedemorton — APPROVED** [review]
Looks great! Thanks for adding this. I noticed a little inconsistency in text you didn't add, so I fixed it.

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
