### PR TITLE
Add docs for Quality Issues table

### PR DESCRIPTION
**Pull request by mdbirnstiehl**
This PR closes [Issue 71583235](https://github.com/orgs/elastic/projects/649/views/43?pane=issue&itemId=71583235).

Adds docs about the quality issues table in the log details flyout.

### CODE REVIEW

**Comment by mdbirnstiehl** [comment]
@yngrdyn will this update be in stateful for 8.15?

**Comment by elasticdocs** [comment]
:rocket: Built _elastic-dot-co-docs-preview-docs_ successfully!

* https://elastic-dot-co-docs-production-17edqi3jx-elastic-dev.vercel.app

* Built with commit f1309790ce6bbcc9b2f6676c50908188cd3df73b

> Issues? Visit #next-docs in Slack

**Comment by yngrdyn** [comment]
> @yngrdyn will this update be in stateful for 8.15?
No, that change didn't make it to `8.15`, it will be released in `8.16`

**Review by yngrdyn — APPROVED** [review]
LGTM

**Review by bmorelli25 — APPROVED** [review]

**Pull request merged**
