### PR TITLE
Remove limitations topic from Fleet and Agent docs

### PR DESCRIPTION
**Pull request by dedemorton**
Closes https://github.com/elastic/observability-docs/issues/856

Removes limitations topic. All relevant info will be moved to the appropriate section in the docs.

TODO: 
- [x] Force the PR build to break to identify broken links across the library.
- [x] ~Open PRs in relevant repos to fix broken links~
- [x] Create redirect page that redirects users to the beats/agent comparison topic
- [x] Move relevant limitations to other locations in the documentation
- [x] Figure out what to do with these limitations. Still valid? If so, where should they go:
  - [x]  In order to use Fleet, the Elastic Agents must have a direct network connection to Kibana and Elasticsearch. It is also possible to run the Elastic Agents in standalone mode in cases where a network connection is not available or not needed.
  - [x] "Fleet is currently only available to users with the superuser role. This role is necessary to create indices, install integration assets, and update Elastic Agent policies."

TODO (after merging):
- [ ] Create redirect request with the web team that goes live on release day
- [ ] Remove redirect page after web team sets up redirects

NOTE: I have not added scaling guidelines to this PR. They should be part of the work Nima is doing on this issue: https://github.com/elastic/observability-docs/issues/523

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Looks good.

Both of these might fit into the prereq section on this page https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html#install-fleet-managed-agent?

* In order to use Fleet, the Elastic Agents must have a direct network connection to Kibana and Elasticsearch. It is also possible to run the Elastic Agents in standalone mode in cases where a network connection is not available or not needed.
* "Fleet is currently only available to users with the superuser role. This role is necessary to create indices, install integration assets, and update Elastic Agent policies."

**Comment by dedemorton** [comment]
> Both of these might fit into the prereq section on this page

Agreed. I think the requirements have changed though. Agent connects to Fleet Server now and can use a proxy server (or will be able to do so after a bug is fixed). Also I can't remember if superuser role is still required for Fleet. I'll wait for @mostlyjason to confirm.

**Comment by mostlyjason** [comment]
@dedemorton looks good. I noticed it doesn't actually remove the limitations page, just adds a redirect. Is that intentional? Also, yes a superuser role is still required.

**Comment by dedemorton** [comment]
@mostlyjason Yes, usually we set up a redirect when possible for moved or deleted pages to avoid 404s. If you think a redirect is confusing, I can remove it. Just let me know.

**Comment by EricDavisX** [comment]
we are pulling out support for Proxy for 7.14 - does that make any impact?  we aren't sure it will be fixed in 7.14.1 or 7.15.

And, about the 'direct connection' statment:
 In order to use Fleet, the Elastic Agents must have a direct network connection to Kibana and Elasticsearch.
shouldn't it rather just be the below?
 In order to use Fleet, the Elastic Agents must have a direct network connection to Fleet Server and Elasticsearch.

**Comment by dedemorton** [comment]
@EricDavisX 

I've added this to the isntall topic: In order to use Fleet, the Elastic Agents must have a direct network connection to Fleet Server and Elasticsearch.

Do you think it also needs to be added to the getting started topics, or are the setup instructions clear enough? My concern is that the list of prereqs is getting quite long, and new users won't know what elastic agents and fleet server are until they run through the steps.

**Comment by EricDavisX** [comment]
I think that is great - and I agree with your thinking about pre-reqs

**Comment by mostlyjason** [comment]
Thanks for adding that to the install topic. Redirect should be fine. Can we publish this now?

Side note: Another option is to mention the requirement for connectivity to Fleet and ES later in the getting started instructions, like when the user is setting up the agent?

**Review by mostlyjason — APPROVED** [review]

**Pull request merged**
