### PR TITLE
Universal Profiling

### PR DESCRIPTION
**Pull request by florianl**
Various updates to Universal Profiling enable us to simplify the documentation.

- [ ] Universal Profiling no longer relys on APM and therefore its reference can be removed
- [ ]  Universal Profiling is no longer hidden in kibana behind `xpack.profiling.enabled`

### CODE REVIEW

**Review by iogbole — APPROVED** [review]
LGTM

**Review by mdbirnstiehl — COMMENTED** [review]
The changes here LGTM, but I believe the profiling-enable-kibana section is linked to from the upgrade guide, which is causing this build to break. Do we need to update the upgrade guide as well?

**Comment by florianl** [comment]
> [..]  profiling-enable-kibana section is linked to from the upgrade guide

good point! I have addressed this by updating the upgrade documentation as well.

**Review by mdbirnstiehl — APPROVED** [review]
I suggested one small update so we have a link to the Get started docs, but otherwise LGTM!

**Pull request merged**
