### PR TITLE
Remove Elastic Serverless Forwarder source files from the obs guide (main branch only)

### PR DESCRIPTION
**Pull request by dedemorton**
Replaces https://github.com/elastic/observability-docs/pull/2848, which was reverted.

TODO:
- [x] Check for late commits that might have gotten added after this PR was created. Make sure they get added to the new location in the elastic-serverless-forwarder repo.

After merging:
- [ ] Set up redirects.
- [ ] Make sure we link to new location of these docs from the obs guide. 
- [ ] Add something to the 8.8 What's New?

### CODE REVIEW

**Comment by dedemorton** [comment]
https://github.com/elastic/observability-docs/pull/2853

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by bmorelli25 — APPROVED** [review]
🚢

**Pull request merged**
