### PR TITLE
Add logs section

### PR DESCRIPTION
**Pull request by ChrsMark**

### CODE REVIEW

**Comment by ChrsMark** [comment]
Opening this for an initial review and start a discussion about specific items. I didn't remove the initial parts' description so as to have it for reference for now until we reach to a final content.  @dedemorton @masci would love your input :)

**Comment by dedemorton** [comment]
The preview is 404ing for me. Let me try to run the doc build again

@elasticmachine run elasticsearch-ci/doc

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/doc

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/doc rebuild

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by dedemorton** [comment]
@ChrsMark Let's discuss how you want to proceed here because we have a couple of options:

1. Use this review to make sure the details are accurate and complete (ignoring editorial/structural/flow issues).
2. Do a more comprehensive review before we merge this into the feature branch.

Option 1 works well for me because I start with raw content and can edit the source files directly (much easier than carpet bombing the review with 200 suggestions). I also don't have to worry as much about preserving the original author's voice.

If you choose option 2, you should remove the descriptions left over from the outline, and add proper headings/steps/formatting, where appropriate, to make the content easier to read and review.

I want to do whatever works best for you.

WDYT?

**Comment by ChrsMark** [comment]
@dedemorton I'm ok with option 1. Let's ensure the content together here and then feel free to touch anything related to wording/flow etc. Is this what option 1 proposes?

**Comment by dedemorton** [comment]
>  Let's ensure the content together here and then feel free to touch anything related to wording/flow etc. Is this what option 1 proposes?

@ChrsMark That's right. We just check for accuracy and completeness, then I do a full edit after the content is merged into our feature branch.

**Comment by ChrsMark** [comment]
> > Let's ensure the content together here and then feel free to touch anything related to wording/flow etc. Is this what option 1 proposes?
> 
> @ChrsMark That's right. We just check for accuracy and completeness, then I do a full edit after the content is merged into our feature branch.

:+1: Let's go with it

**Comment by dedemorton** [comment]
@ChrsMark Looked through the content, and I think there's enough here for me to get started working. I think it will be more efficient if you just merge your two PRs into the feature branch. Then after I've done my work, we can use the PR I have open (https://github.com/elastic/observability-docs/pull/151) for the review. The previews will work, and we'll be able to see all the content in one place. WDYT?

**Review by dedemorton — APPROVED** [review]
We should go ahead and merge this in the feature branch so I can iterate on it.

**Pull request merged**
