### PR TITLE
[Docs] Update cross-document links to Kibana Alerting docs

### PR DESCRIPTION
**Pull request by ymao1**
Some recent PRs have moved around some of the alerting docs within the Kibana docs, so some of the links need to be updated.

Relevant PRs:
* https://github.com/elastic/kibana/pull/101323
* https://github.com/elastic/kibana/pull/101498
* https://github.com/elastic/kibana/pull/101420

### CODE REVIEW

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
Running docs build again because it looks like the link was broken when the CI ran originally.

**Review by bmorelli25 — APPROVED** [review]
Tested each link and everything works. Thanks, @ymao1!

I'll handle the backports to 7.x and 7.13.

**Comment by ymao1** [comment]
@bmorelli25 Sorry! I put the wrong tag. This only needs backporting to 7.x

**Comment by bmorelli25** [comment]
No problem. Thanks!

**Pull request merged**
