### PR TITLE
[Inventory] Remove the new services inventory docs

### PR DESCRIPTION
**Pull request by alaudazzi**
## Description
This PR removes the [new services inventory documentation](https://www.elastic.co/docs/current/serverless/observability/new-experience-services) as it is superseded by the new Inventory page (#4341) .

### Documentation sets edited in this PR

_Check all that apply._

- [ ] Stateful (`docs/en/observability/*`)
- [X] Serverless (`docs/en/serverless/*`)
- [ ] Integrations Developer Guide (`docs/en/integrations/*`)
- [ ] None of the above

### Related issues
- https://github.com/elastic/observability-docs/issues/4254
- https://github.com/elastic/observability-docs/pull/4341

## Checklist

- [X] Product/Engineering Review
- [X] Writer Review

### Follow-up tasks

_Select one._

* This PR does _not_ need to be ported to another doc set because:
  - [ ] The concepts in this PR only apply to one doc set (serverless _or_ stateful)
  - [ ] The PR contains edits to both doc sets (serverless _and_ stateful)
* This PR needs to be ported to another doc set:
  - [X] Port to stateful docs: https://github.com/elastic/observability-docs/issues/4347
  - [ ] Port to serverless docs: \<link to PR or tracking issue>

### CODE REVIEW

**Review by roshan-elastic — DISMISSED** [review]
LGTM!

**Review by colleenmcginnis — COMMENTED** [review]
It looks like there are links to the page you deleted in two files that need to be updated or removed:

* [`docs/en/serverless/elastic-entity-model.mdx`](https://github.com/alaudazzi/observability-docs/blob/issue-4254-remove-service-inventory/docs/en/serverless/elastic-entity-model.mdx?plain=1#L25-L35) (2 instances)
* [`docs/en/serverless/apm/apm-ui-services.mdx`](https://github.com/alaudazzi/observability-docs/blob/issue-4254-remove-service-inventory/docs/en/serverless/apm/apm-ui-services.mdx?plain=1#L25) (1 instance)

**Comment by alaudazzi** [comment]
Thank you for your review @colleenmcginnis!
I updated the [docs/en/serverless/apm/apm-ui-services.mdx](https://github.com/alaudazzi/observability-docs/blob/issue-4254-remove-service-inventory/docs/en/serverless/apm/apm-ui-services.mdx?plain=1#L25) by removing the reference for now. When we have more solid content for Inventory, we can put it back, if needed.

[docs/en/serverless/elastic-entity-model.mdx](https://github.com/alaudazzi/observability-docs/blob/issue-4254-remove-service-inventory/docs/en/serverless/elastic-entity-model.mdx?plain=1#L25-L35) is being updated in https://github.com/elastic/observability-docs/pull/4340, so broken links are expected.

**Review by roshan-elastic — APPROVED** [review]

**Review by mdbirnstiehl — APPROVED** [review]
🦭

**Comment by elasticdocs** [comment]
:rocket: Built _elastic-dot-co-docs-preview-docs_ successfully!

* https://elastic-dot-co-docs-production-9r4k8w0bb-elastic-dev.vercel.app

* Built with commit 1823eb67341c8b1d0ecafde5ab2e064b647cbab5

> Issues? Visit #next-docs in Slack

**Pull request merged**
