### PR TITLE
Update APM URLs

### PR DESCRIPTION
**Pull request by bmorelli25**
### Summary

This PR updates our APM documentation by prepending the APM documentation paths with `apm-`.

### Task list
- [x] **[Pre-req]** Remove old release note redirects https://github.com/elastic/observability-docs/pull/3688
- [x] **[Pre-req]** Update release note URLs https://github.com/elastic/apm-server/pull/12820
- [x] **[Pre-req]** Create and test redirect list **([WIP Google Sheet](https://docs.google.com/spreadsheets/d/1EXF-ddCijpvJbnG-8OiASImXhp0KeP0o4JDpVvn7UC0/edit#gid=0))**
- [x] **[This PR]** Revert [#3688](#3688) and add new redirects for release notes
- [x] **[This PR]** Update all URL paths to include `apm-`
- [ ] **[after merge]** Request 301 redirects from marketing

### URLs not updated

The following URLs had paths already prepended with `apm-` and thus do not need redirects:

```
/apm.html
/apm-agent-auth.html
/apm-breaking.html
/apm-data-security.html
/apm-data-streams.html
/apm-distributed-tracing.html
/apm-integration-upgrade-steps.html
/apm-integration-upgrade-steps-ess.html
/apm-integration-upgrade-steps.html
/apm-k8s-attacher.html
/apm-mutating-admission-webhook.html
/apm-rum.html
/apm-server-configuration.html
/apm-server-starting.html
```

### Related

For https://github.com/elastic/observability-docs/issues/3573.

### Process

Documenting my process below in case we need to make similar changes in the future. Note that this is absolutely not performant, but it somehow does work! The bash file in step two takes ~3 minutes to run.

1. I replaced all APM headings in VSC:
```txt
Find: \[\[(.+)\]\]
Replace: [[apm-$1]]
Include: docs/en/observability/apm
```

2. I found all headings in the APM documentation that were prepended with `apm-*`. For each heading, this script searches for links missing `apm-*` and automatically adds them.
```bash
grep -Rih "\[\[apm-" /Users/brandon/Documents/GitHub/observability-docs/docs/en/observability/apm > headings.txt
cat headings.txt | while read line
do
  data=$(echo $line | sed -r 's/\[\[apm-(.*)\]\]$/\1/')
  echo $data
  # Update internal links
  sed -i '' "s/\<\<$data/\<\<apm-$data/g" $(find . -type f -name "*.asciidoc" 2>/dev/null)
  # Update external links (mostly in redirects file)
  sed -i '' "s/\observability-guide\}\/$data/\observability-guide\}\/apm-$data/g" $(find . -type f -name "*.asciidoc" 2>/dev/null)
done
```

### CODE REVIEW

**Comment by bmorelli25** [comment]
Broken links:

```

2024-03-14 00:48:22 UTC | INFO:build_docs:Bad cross-document links:
-- | --
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/agent-tls.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-agent-tls.html#agent-client-cert
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/api-metadata.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-metadata.html#api-metadata-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/concurrent_requests.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-process.html#configuration-apm-server
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/configuration-process.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-process.html#max_event_size
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/configuration-rum.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-rum.html#rum-allow-origins
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-rum.html#rum-library-pattern
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/configuration-v1-api.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-process.html#configuration-apm-server
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/configuration-v2-api.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-process.html#configuration-apm-server
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/data-model-metadata.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-data-model-metadata.html#data-model-custom
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-data-model-metadata.html#data-model-labels
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/data-model-spans.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-data-model-spans.html#data-model-dropped-spans
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/error-context-schema.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/error-payload-schema.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/error-schema-definition.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/error-service-schema.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/error-stacktraceframe-schema.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/error-system-schema.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/max_request_queue_time.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-process.html#configuration-apm-server
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/max_unzipped_size.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-process.html#configuration-apm-server
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/metrics.enabled.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-process.html#configuration-apm-server
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/payload-with-error.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/payload-with-minimal-exception.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/payload-with-minimal-log.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-error.html#api-error-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.0.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.0.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.1.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.1.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.10.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.10.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.11.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.11.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.2.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.2.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.3.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.3.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.4.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.4.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.5.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.5.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.6.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.6.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.7.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.7.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.8.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.8.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/release-notes-8.9.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-release-notes-8.9.html
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/source-map-how-to.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-source-map-how-to.html#source-map-rum-generate
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-source-map-how-to.html#source-map-rum-upload
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/transaction-schema-definition.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-api-transaction.html#api-transaction-schema
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/use-v1-and-v2.html contains broken links to:
  | 2024-03-14 00:48:22 UTC | INFO:build_docs:   - en/observability/master/apm-tune-data-ingestion.html#tune-apm-server


```

**Comment by bmorelli25** [comment]
A couple more:

```

2024-03-14 02:05:31 UTC | INFO:build_docs:Bad cross-document links:
-- | --
  | 2024-03-14 02:05:31 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/configuration-rum.html contains broken links to:
  | 2024-03-14 02:05:31 UTC | INFO:build_docs:   - en/observability/master/apm-configuration-rum.html#apm-rum-library-pattern
  | 2024-03-14 02:05:31 UTC | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/master/ilm-how-to.html contains broken links to:
  | 2024-03-14 02:05:31 UTC | INFO:build_docs:   - en/observability/master/apm-ilm-how-to.html#apm-data-streams-custom-policy


```

**Comment by simitt** [comment]
@bmorelli25 the broken links sections mean, that these links will forward to the new pages?

**Comment by bmorelli25** [comment]
> @bmorelli25 the broken links sections mean, that these links will forward to the new pages?

Sorry, those comments were for me for debugging purposes. You can ignore them.

> I'm generally +1 on the changes, but it doesn't update the release note URLs, which I think are especially misleading with e.g. https://www.elastic.co/guide/en/observability/current/release-notes-8.12.html. Is this something that you intend to pick up later?

Fair point. Working on that in conjunction with this PR now.

**Comment by bmorelli25** [comment]
Okay, this PR is ready for review again. This PR prepends all APM URLs, including release note URLs, with `apm-`. I plan on merging this PR and backporting to 8.13. When the 8.13 release goes out, we'll ask marketing to implement the redirects listed in [this google sheet](https://docs.google.com/spreadsheets/d/1EXF-ddCijpvJbnG-8OiASImXhp0KeP0o4JDpVvn7UC0/edit#gid=0).

**Review by simitt — APPROVED** [review]
LGTM; 
@bmorelli25 are you taking care of the follow up actions mentioned in https://github.com/elastic/observability-docs/issues/3573? 
Please also be aware that https://github.com/elastic/infra/pull/40558/files has been merged in the meant time, and you'll need to collaborate with @jmlrt on updating the URLs in a follow up PR.

**Review by mdbirnstiehl — APPROVED** [review]
👍

**Review by mdbirnstiehl — APPROVED** [review]
🐦

**Pull request merged**
