### PR TITLE
Add quick start to Integrations Dev Guide

### PR DESCRIPTION
**Pull request by kilfoyle**
This adds a Quick Start guide for building, uploading, and testing a custom integration package. Contents are based off of Nicolas' [very nice demo](https://github.com/ruflin/ruflin-integration-package). I've tested everything locally using an 8.12.2 stack.

Please see [DOCS PREVIEW PAGE](https://observability-docs_bk_3845.docs-preview.app.elstc.co/guide/en/integrations-developer/current/quick-start.html)

Closes: https://github.com/elastic/ingest-docs/issues/1054

### CODE REVIEW

**Comment by Oddly** [comment]
Hi David,
I've recently created an internal integration at my company and this would've really helped back then, so great job here.
If you don't mind, I've got two small suggestions to consider.

- Would it be interesting to note that the install command is also able to install the package directly into an existing cluster for testing? Depending on whether it's officially supported.
- You can also use the `elastic-package changelog` command to add a changelog entry instead of manually editing the files.

**Comment by agithomas** [comment]
Can we have a mention of semantic versioning below the section `Step 5: Release a new version` ?

Reference : https://github.com/elastic/obs-infraobs-team/issues/1145

We may not have a page yet to explain about semantic versioning. But, a one-liner to indicate the expectation would be useful to the developers. We observe frequent mistakes related to version numbering when we do code reviews.

**Comment by agithomas** [comment]
One of the sections on the [Ruflin integration package ](https://github.com/ruflin/ruflin-integration-package )GitHub page is  "Done,  encourages community contributions to the elastic stack.


In this GitHub [comment]((https://github.com/elastic/obs-infraobs-team/issues/1222#issuecomment-1895006447)), there are references to resources such as "Promote your Integration with Elastic in the Community" and "Registering on Elastic's Partner Portal as a Technology Partner."


Would it be beneficial to include a "what next?" section, or something similar, on the Ruflin integration package page? This section would contain the information from the "Done" section, along with the provided resources, to guide users on how to explore further and contribute.


```
Promote your Integration with Elastic in the Community:
https://www.elastic.co/community/

Registering on Elastic's Partner Portal as a Technology Partner:
https://partners.elastic.co/English/register_email.aspx
```


In the absence of @SubhrataK , @vinaychandrasekhar , can you please share your opinion ?

**Comment by kilfoyle** [comment]
@Oddly  Thanks for your feedback! I'm glad you like the guide.

> Would it be interesting to note that the install command is also able to install the package directly into an existing cluster for testing? Depending on whether it's officially supported.

Definitely. This is documented in the How To guide so Iwe can include it here. I've added this note:

Screenshot 2024-05-03 at 12 36 02 PM

> You can also use the elastic-package changelog command to add a changelog entry instead of manually editing the files.

Neat! We should probably document this in full, but for now I've just added a note that the `elastic-package changelog` command is an option. I've linked to the integrations repo since that command isn't yet in the reference section of this guide.

Screenshot 2024-05-03 at 12 54 16 PM

**Comment by kilfoyle** [comment]
@agithomas  Thanks for the great suggestions!

> Can we have a mention of semantic versioning below the section Step 5: Release a new version ?

Definitely! I add the following to the bottom of Step 5. Please let me know if it needs any fixing up:

Screenshot 2024-05-03 at 12 56 13 PM

> Would it be beneficial to include a "what next?" (or similar) section

We should have this for sure. Here's what I've added:

screen

Note that for now I've linked to the contributor guidelines for the steps to add dashboards and such. Eventually, I expect we can fix that link to point to this guide, once we've imported the relevant instructions.

**Comment by agithomas** [comment]
The changes LGTM!

**Comment by agithomas** [comment]
++ @lalit-satapathy.

**Comment by bmorelli25** [comment]
Thank you Agi and David! I'm not sure if Lalit has had a chance to look at this yet. I'll merge in 24 hours 🎉 .

**Comment by alaudazzi** [comment]
@kilfoyle Thank you for compiling some of the pieces of what seems to be a big puzzle.
I need more time to review this content reorg, but I don't want to block the merge of this PR. 
I'll get back to this portion of the Integrations docs soon and provide feedback where needed.

**Review by bmorelli25 — APPROVED** [review]
🦖

**Pull request merged**
