### PR TITLE
Remove unneed code marking in monitor-amazon-sqs section

### PR DESCRIPTION
**Pull request by OrekiYuta**
https://www.elastic.co/guide/en/observability/current/monitor-amazon-sqs.html

remove unuse var marker
image

### CODE REVIEW

**Comment by bmorelli25** [comment]
Thanks, @OrekiYuta. Can you please fill out the CLA linked above.

**Comment by bmorelli25** [comment]
run docs-build

**Comment by OrekiYuta** [comment]
> Thanks, @OrekiYuta. Can you please fill out the CLA linked above.

Hi, @bmorelli25, I filled out the CLA 3 days ago, but I haven't received any updates yet. Could you please help with this? Thanks a lot!

**Comment by OrekiYuta** [comment]
Hi @bmorelli25 , All checks have passed, could you help to approving review? thanks a lot!

**Review by bmorelli25 — APPROVED** [review]

**Comment by bmorelli25** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|main|[](https://github.com/elastic/observability-docs/pull/4009)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
