### PR TITLE
update name to Elastic Cloud agent

### PR DESCRIPTION
**Pull request by EricDavisX**
fixes: https://github.com/elastic/observability-docs/issues/733

just a quick edit to align to final product naming.  naming is hard!  :)

Screen Shot 2021-06-01 at 3 09 44 PM

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Thank you!

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have observed that the name for Elastic Cloud agent policy is still not updated for 7.13 docs.

**Reference:**  https://github.com/elastic/observability-docs/issues/733 

**Screenshots:**
https://www.elastic.co/guide/en/fleet/7.13/fleet-quick-start.html#set-up-fleet


https://www.elastic.co/guide/en/fleet/master/fleet-troubleshooting.html#_check_the_elastic_agent_status


Thanks
QAS

**Comment by EricDavisX** [comment]
@bmorelli25 hi, it looks like the PRs were open from a few weeks back.  I reviewed and merged -let me know if I was supposed to (ideally) push it on, I hadn't been following up, I realize.

Also, I'm not sure when they will be (re)published again or if they are 'live' within a certain time frame after they are merged or what.  can you help confirm what expectations the team should have at this point?  Thank you!  

@amolnater-qasource let's retest based on what Brandon says

**Comment by bmorelli25** [comment]
> @bmorelli25 hi, it looks like the PRs were open from a few weeks back. I reviewed and merged -let me know if I was supposed to (ideally) push it on, I hadn't been following up, I realize.

Oops. That's on me. I totally forgot to merge those PRs. Thank you, @amolnater-qasource! In general, in the observability-docs repo, whoever merges the original PR is responsible for the backport PRs. In this case, you added the branch labels so I took it on myself to handle backports and clearly only handled half of the process.

> Also, I'm not sure when they will be (re)published again or if they are 'live' within a certain time frame after they are merged or what. can you help confirm what expectations the team should have at this point? Thank you!

Our doc build runs every thirty minutes and then propagates changes within 10 minutes of the build. This means that once a PR has been merged, it can take anywhere from 10-40 mins to see the changes live. In this case, it looks like the changes are showing up on the website already:

Screen Shot 2021-06-14 at 10 37 47 AM

It looks like we don't have a PR fix up for the second example, so I'll open that right now.

**Comment by EricDavisX** [comment]
Thanks Brandon - I appreciate the help and info. Cheers!

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated these links and found it **fixed** now.
- Names for Elastic Cloud agent policy is updated at both the links.

**Screenshots:**
https://www.elastic.co/guide/en/fleet/7.13/fleet-quick-start.html#set-up-fleet


https://www.elastic.co/guide/en/fleet/master/fleet-troubleshooting.html#_check_the_elastic_agent_status


Thanks
QAS

**Pull request merged**
